{% set name = "rejson" %}
{% set version = "0.5.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rejson-{{ version }}.tar.gz
  sha256: 2e29444da6e939008374466812e96c7d9c6cf6e75a6e4928391575245353daa3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - redis-py >=3.0.0
    - six >=1.10

test:
  imports:
    - rejson
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/RedisLabs/rejson-py
  summary: ReJSON Python Client
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
